name: intersection_traffic_meter

parameters:
  frame:
    width: 1920
    height: 1080
  output_frame:
    codec: ${oc.env:CODEC, 'h264'}
  draw_func:
    module: samples.intersection_traffic_meter.overlay
    class_name: Overlay
    kwargs:
      config_path: ${oc.env:PROJECT_PATH}/samples/intersection_traffic_meter/polygon_config.yml
  detected_object_label: transport
  send_stats: True
  batch_size: 1

pipeline:

  elements:

    - element: nvinfer@detector
      name: yolov8m
      model:
        remote:
          url: s3://savant-data/models/yolov8m_f630b10/yolov8m_f630b10.zip
          checksum_url: s3://savant-data/models/yolov8m_f630b10/yolov8m_f630b10.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        model_file: yolov8m.onnx
        config_file: config_infer_primary_yoloV8.txt
        # max GPU RAM used to build the engine, 6GB by default
        # set lower than total GPU RAM available on your hardware
        workspace_size: 6144
        output:
          objects:
            # COCO bicycle
            - class_id: 1
              label: ${parameters.detected_object_label}
              selector:
                module: savant.selector.detector
                class_name: BBoxSelector
                kwargs:
                  confidence_threshold: 0.2
            # COCO car
            - class_id: 2
              label: ${parameters.detected_object_label}
              selector:
                module: savant.selector.detector
                class_name: BBoxSelector
                kwargs:
                  confidence_threshold: 0.2
            # COCO motorcycle
            - class_id: 3
              label: ${parameters.detected_object_label}
              selector:
                module: savant.selector.detector
                class_name: BBoxSelector
                kwargs:
                  confidence_threshold: 0.2
            # COCO bus
            - class_id: 5
              label: ${parameters.detected_object_label}
              selector:
                module: savant.selector.detector
                class_name: BBoxSelector
                kwargs:
                  confidence_threshold: 0.2
            # COCO truck
            - class_id: 7
              label: ${parameters.detected_object_label}
              selector:
                module: savant.selector.detector
                class_name: BBoxSelector
                kwargs:
                  confidence_threshold: 0.2

