name: intersection_traffic_meter

parameters:
  output_frame:
    codec: ${oc.env:CODEC, 'h264'}
    h264_encoder_params:
      bitrate: 8000000
      profile: Baseline
  draw_func:
    module: samples.intersection_traffic_meter.overlay
    class_name: Overlay
    kwargs:
      config_path: ${oc.env:PROJECT_PATH}/samples/intersection_traffic_meter/polygon_config.yml
  detected_object_label: transport
  send_stats: True
  batch_size: 1

  default_yolo_converter:
    module: savant.converter.yolo
    class_name: TensorToBBoxConverter
    kwargs:
      confidence_threshold: 0.25
      nms_iou_threshold: 0.45
      top_k: 300

  default_yolo_selector:
    module: savant.selector.detector
    class_name: MinMaxSizeBBoxSelector
    kwargs:
      min_width: 30
      min_height: 30


pipeline:

  elements:

    - element: pyfunc
      module: samples.intersection_traffic_meter.line_crossing
      class_name: ConditionalDetectorSkip
      kwargs:
        config_path: ${oc.env:PROJECT_PATH}/samples/intersection_traffic_meter/polygon_config.yml

    - element: nvinfer@detector
      name: yolov11n
      model:
        remote:
          url: s3://savant-data/models/yolo11n/yolo11n.zip
          checksum_url: s3://savant-data/models/yolo11n/yolo11n.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com              
        format: onnx
        model_file: yolo11n.onnx
        batch_size: ${parameters.batch_size}
        workspace_size: 6144
        input:
          shape: [3, 640, 640]
          scale_factor: 0.0039215697906911373
          maintain_aspect_ratio: true
          symmetric_padding: true
        output:
          layer_names: [output0]
          num_detected_classes: 80  # required for YOLOv11
          converter: ${parameters.default_yolo_converter}
          objects:
            # COCO bicycle
            - class_id: 1
              label: ${parameters.detected_object_label}
              selector: ${parameters.default_yolo_selector}
            # COCO car
            - class_id: 2
              label: ${parameters.detected_object_label}
              selector: ${parameters.default_yolo_selector}
            # COCO motorcycle
            - class_id: 3
              label: ${parameters.detected_object_label}
              selector: ${parameters.default_yolo_selector}
            # COCO bus
            - class_id: 5
              label: ${parameters.detected_object_label}
              selector: ${parameters.default_yolo_selector}
            # COCO truck
            - class_id: 7
              label: ${parameters.detected_object_label}
              selector: ${parameters.default_yolo_selector}

    - element: nvtracker
      properties:
        ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
        ll-config-file: ${oc.env:PROJECT_PATH}/samples/assets/tracker/config_tracker_NvDCF_perf.yml
        tracker-width: 960  # 640  # must be a multiple of 32
        tracker-height: 544  # 384
        display-tracking-id: 0

    - element: pyfunc
      module: samples.intersection_traffic_meter.line_crossing
      class_name: LineCrossing
      kwargs:
        config_path: ${oc.env:PROJECT_PATH}/samples/intersection_traffic_meter/polygon_config.yml
        stale_track_del_period: 5000
        target_obj_label: ${parameters.detected_object_label}
        send_stats: ${parameters.send_stats}
