services:

  gige-camera-raw:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.11
    extends:
      file: docker-compose.l4t.yml
      service: gige-camera-raw

  gige-camera-encoded:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.11
    extends:
      file: docker-compose.l4t.yml
      service: gige-camera-encoded

  gige-source-raw:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.11
    extends:
      file: docker-compose.l4t.yml
      service: gige-source-raw

  gige-source-encoded:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.11
    extends:
      file: docker-compose.l4t.yml
      service: gige-source-encoded

  always-on-sink:
    privileged: true
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.5.11-7.0
    extends:
      file: docker-compose.l4t.yml
      service: always-on-sink
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  zmq_sockets:
