# module name, required
name: buffer_adapter_demo

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
  output_frame:
    codec: ${oc.env:CODEC, 'h264'}
  # PyFunc for drawing on frames
  draw_func: {}
  batch_size: 1

# pipeline definition
pipeline:
  # source definition is skipped, zeromq source is used by default to connect with source adapters

  # define pipeline's main elements
  elements:
    # emulate lag in the pipeline
    - element: pyfunc
      # specify the pyfunc's python module
      module: samples.buffer_adapter.lag_generator
      # specify the pyfunc's python class from the module
      class_name: LagGenerator
      # pyfunc's class init keyword arguments
      # will be available as pyfunc object's attributes
      kwargs:
        # minimal lag in seconds
        min_lag: 0.06
        # maximal lag in seconds
        max_lag: 0.1
        # lagged frames sequence length
        lag_frames_interval: 500
        # non-lagged frames sequence length
        pass_frames_interval: 500

    # primary detector element, inference is provided by the nvinfer Deepstream element
    # model type is detector (other available types are: classifier, custom)
    - element: nvinfer@detector
      # Model's name in the pipeline, mandatory
      name: peoplenet
      # model definition
      model:
        # format of the provided model file
        format: etlt
        # remote storage where the model files can be found
        # skip if providing model files locally
        remote:
          url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.zip
          checksum_url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
          # or get the model directly from NGC API
          # peoplenet v2.0
          # url: "https://api.ngc.nvidia.com/v2/models/nvidia/tao/peoplenet/versions/pruned_v2.0/zip"

        # model file name, without location
        model_file: resnet34_peoplenet_pruned.etlt  # v2.0 Accuracy: 84.3 Size 20.9 MB
        batch_size: ${parameters.batch_size}

        # configuration of input data and custom preprocessing methods
        input:
          # model input layer name
          layer_name: input_1
          # model input layer shape
          shape: [3, 544, 960]
          # pixel scaling/normalization factor
          scale_factor: 0.0039215697906911373

        # configuration of model output
        output:
          # model output layer names
          layer_names: [output_bbox/BiasAdd, output_cov/Sigmoid]
          # number of detected classes for detector model
          num_detected_classes: 3
          # specify which detected objects are included in output
          objects:
            # object class id
            - class_id: 0
              # label assigned to objects of this class id
              label: person
              selector:
                kwargs:
                  # minimal width of the objects of this class to be included in output
                  min_width: 32
                  # minimal height of the objects of this class to be included in output
                  min_height: 32

  # sink definition is skipped, zeromq sink is used by default to connect with sink adapters
