services:

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
    extends:
      file: docker-compose.l4t.yml
      service: video-loop-source

  buffer:
    image: ghcr.io/insight-platform/savant-buffer-ng-x86:savant-latest
    extends:
      file: docker-compose.l4t.yml
      service: buffer

  module:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream:latest
    extends:
      file: docker-compose.l4t.yml
      service: module
    runtime: runc
    environment:
      - CODEC=h264
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  always-on-sink:
    privileged: true
    image: ghcr.io/insight-platform/savant-adapters-deepstream:latest
    extends:
      file: docker-compose.l4t.yml
      service: always-on-sink
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  prometheus:
    extends:
      file: docker-compose.l4t.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.l4t.yml
      service: grafana

volumes:
  buffer:
  zmq_sockets:
  message_dump:
