services:

  client:
    image: ghcr.io/insight-platform/savant-deepstream:0.5.11-7.0
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ./client.py:/opt/savant/client.py
      - ./data:/data
    environment:
      - ZMQ_SRC_ENDPOINT=req+connect:ipc:///tmp/zmq-sockets/input.ipc
      - ZMQ_SINK_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output.ipc
      - LOGLEVEL=info,savant_core::pipeline::stats=error
    entrypoint: python
    command: client.py
    depends_on:
      module:
        condition: service_healthy

  module:
    image: ghcr.io/insight-platform/savant-deepstream:0.5.11-7.0
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ./cache:/cache
      - ./module.yml:/opt/savant/module.yml
      - ./data:/data
    command: module.yml
    environment:
      - MODEL_PATH=/cache/models
      - DOWNLOAD_PATH=/cache/downloads
      - ZMQ_SRC_ENDPOINT=rep+bind:ipc:///tmp/zmq-sockets/input.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output.ipc
      - LOGLEVEL=info,savant_core::pipeline::stats=error
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  zmq_sockets:
