services:

  image-json-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.14
    extends:
      file: docker-compose.l4t.yml
      service: image-json-source

  module:
    privileged: true
    build:
      context: .
      dockerfile: docker/Dockerfile.x86
    extends:
      file: docker-compose.l4t.yml
      service: module
    runtime: runc
    environment:
      - CODEC=jpeg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  image-json-sink:
    image: ghcr.io/insight-platform/savant-adapters-py:0.5.14
    extends:
      file: docker-compose.l4t.yml
      service: image-json-sink

volumes:
  zmq_sockets:
