services:

  client:
    image: ghcr.io/insight-platform/savant-deepstream:latest
    extends:
      file: docker-compose.l4t.yml
      service: client

  uri-input:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream:latest
    extends:
      file: docker-compose.l4t.yml
      service: uri-input
    runtime: runc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  module:
    privileged: true
    build:
      context: .
      dockerfile: docker/Dockerfile.x86
    extends:
      file: docker-compose.l4t.yml
      service: module
    runtime: runc
    environment:
      - CODEC=h264
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  jaeger:
    extends:
      file: docker-compose.l4t.yml
      service: jaeger

  always-on-sink:
    privileged: true
    image: ghcr.io/insight-platform/savant-adapters-deepstream:latest
    extends:
      file: docker-compose.l4t.yml
      service: always-on-sink
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  zmq_sockets:

networks:
  network:
    attachable: true
