services:

  video-loop-source-720p:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.13
    extends:
      file: docker-compose.l4t.yml
      service: video-loop-source-720p

  video-loop-source-1080p:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.13
    extends:
      file: docker-compose.l4t.yml
      service: video-loop-source-1080p

  module:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream:0.5.13-7.0
    extends:
      file: docker-compose.l4t.yml
      service: module
    runtime: runc
    environment:
      - CODEC=h264
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  always-on-sink:
    privileged: true
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.5.13-7.0
    extends:
      file: docker-compose.l4t.yml
      service: always-on-sink
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  zmq_sockets:
