version: "3.3"
services:
  module:
    build:
      context: .
      dockerfile: docker/Dockerfile.x86
    volumes:
      - ../../models/traffic_meter:/models
      - ../../downloads/traffic_meter:/downloads
      - .:/opt/savant/samples/traffic_meter
    command: samples/traffic_meter/module.yml
    environment:
      - ZMQ_SRC_ENDPOINT=sub+bind:tcp://0.0.0.0:3331
      - ZMQ_SINK_ENDPOINT=pub+bind:tcp://0.0.0.0:3332
      - METRICS_FRAME_PERIOD=1000
      - DETECTOR=${DETECTOR}
      - MODULE_NAME=traffic_meter-${DETECTOR}
    ports:
      - "3331:3331"
      - "3332:3332"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - ./graphite-storage:/opt/graphite/storage
  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana_datasources:/etc/grafana/provisioning/datasources/
      - ./grafana_dashboards:/etc/grafana/provisioning/dashboards/
      - grafana_data:/var/lib/grafana/
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

volumes:
  grafana_data:
