# build nvinfer custom library for yolo models (create engine and parse bbox functions)
# https://github.com/marcoslucianops/DeepStream-Yolo
FROM nvcr.io/nvidia/deepstream-l4t:6.2-triton as builder

ENV CUDA_VER=11.4
ARG DS_YOLO_VER=f630b10a8088398251bca7f2f50064b57fab06bb
ARG DS_YOLO_PATH=/opt/yolo
ARG NVDSINFER_PATH=/opt/nvidia/deepstream/deepstream/sources/libs/nvdsinfer

RUN git clone https://github.com/marcoslucianops/DeepStream-Yolo.git $DS_YOLO_PATH \
    && cd $DS_YOLO_PATH \
    && git checkout $DS_YOLO_VER \
    && make -C nvdsinfer_custom_impl_Yolo

# patch nvdsinfer_model_builder.cpp: use engine path to place created engine
COPY nvdsinfer_model_builder.patch $NVDSINFER_PATH/
RUN cd $NVDSINFER_PATH && \
    patch nvdsinfer_model_builder.cpp < nvdsinfer_model_builder.patch && \
    make

FROM ghcr.io/insight-platform/savant-deepstream-l4t:latest

ARG DS_YOLO_PATH=/opt/yolo
ARG NVDSINFER_PATH=/opt/nvidia/deepstream/deepstream/sources/libs/nvdsinfer

COPY --from=builder $DS_YOLO_PATH/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so /opt/savant/lib/
COPY --from=builder $NVDSINFER_PATH/libnvds_infer.so /opt/nvidia/deepstream/deepstream/lib/
