name: ${oc.env:MODULE_NAME, 'demo'}

parameters:
  frame:
    width: 1280
    height: 720
    padding:
      keep: true
      left: 0
      right: 0
      top: 180
      bottom: 0
  output_frame:
    codec: h264
  draw_func:
    module: samples.peoplenet_detector.overlay
    class_name: Overlay
    kwargs:
      face_bbox_border_color: [1, 0.5, 0.5]
      person_with_face_bbox_color: [0, 1, 0]
      person_no_face_bbox_color: [1, 0, 0]
      person_label_bg_color: [1, 0.9, 0.85]
      person_label_font_color: [0, 0, 0]
      bbox_border_width: 3
      overlay_height: 180
      logo_height: 120
      sprite_heigth: 120
      counters_height: 85
      counters_font_thickness: 5

pipeline:
  elements:
    - element: nvinfer@detector
      name: peoplenet
      model:
        format: etlt
        remote:
          url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.zip
          checksum_url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
          # or get the model directly from NGC API
          # peoplenet v2.0
          # url: "https://api.ngc.nvidia.com/v2/models/nvidia/tao/peoplenet/versions/pruned_v2.0/zip"

        model_file: resnet34_peoplenet_pruned.etlt  # v2.0 Accuracy: 84.3 Size 20.9 MB

        input:
          layer_name: input_1
          shape: [3, 544, 960]
          scale_factor: 0.0039215697906911373
        output:
          layer_names: [output_bbox/BiasAdd, output_cov/Sigmoid]
          num_detected_classes: 3
          objects:
            - class_id: 0
              label: person
              selector:
                kwargs:
                  min_width: 32
                  min_height: 32
            - class_id: 2
              label: face
              selector:
                kwargs:
                  confidence_threshold: 0.1

    - element: nvtracker
      properties:
        tracker-width: 640
        tracker-height: 384
        ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
        ll-config-file: ${oc.env:APP_PATH}/samples/peoplenet_detector/config_tracker_NvSORT.yml
        enable_batch_process: 1
    
    - element: pyfunc
      module: samples.peoplenet_detector.analytics
      class_name: Analytics
      kwargs:
        counters_smoothing_period: 0.25
