version: "3.3"
services:

#  video-loop-source:
#    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
#    restart: unless-stopped
#    volumes:
#      - zmq_sockets:/tmp/zmq-sockets
#      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
#    environment:
#      - LOCATION=https://eu-central-1.linodeobjects.com/savant-data/demo/Free_City_Street_Footage.mp4
#      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
#      - ZMQ_ENDPOINT=pub+connect:ipc:///tmp/zmq-sockets/input-video.ipc
#      - SOURCE_ID=city-traffic
#      - SYNC_OUTPUT=True
#    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh

  module:
    build:
      context: .
      dockerfile: docker/Dockerfile.x86
    restart: unless-stopped
    volumes:
      - /tmp/zmq-sockets:/tmp/zmq-sockets
      - ../../models/peoplenet_detector:/models
      - ../../downloads/peoplenet_detector:/downloads
      - ..:/opt/savant/samples
    command: samples/peoplenet_detector/demo.yml
    environment:
      - ZMQ_SRC_ENDPOINT=sub+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_SINK_ENDPOINT=pub+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - FPS_PERIOD=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

#  image-json-sink:
#    image: ghcr.io/insight-platform/savant-adapters-gstreamer:latest
#    restart: unless-stopped
#    volumes:
#      - zmq_sockets:/tmp/zmq-sockets
#      - ../../data/results:/results
#    environment:
#      - ZMQ_ENDPOINT=sub+connect:ipc:///tmp/zmq-sockets/output.ipc
#      - CHUNK_SIZE=1000
#      - DIR_LOCATION=/results
#    entrypoint: /opt/savant/adapters/gst/sinks/video_files.sh


volumes:
  zmq_sockets: