name: ${oc.env:MODULE_NAME, 'regular-cam-human-detector-peoplenet'}

parameters:
  frame_width: ${initializer:frame_width, 960}
  frame_height: ${initializer:frame_height, 544}
  person_min_height: ${initializer:person_min_height, 16}
  output_frame: ${json:${oc.env:OUTPUT_FRAME, '{"codec":"jpeg"}'}}

pipeline:
  # define elements
  elements:
    - element: nvinfer@detector
      name: peoplenet
      model:
        format: etlt
        remote:
          url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.zip
          checksum_url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
          # or get the model directly from NGC API
          # peoplenet v2.0
          # url: "https://api.ngc.nvidia.com/v2/models/nvidia/tao/peoplenet/versions/pruned_v2.0/zip"
          # peoplenet v2.6
          # url: "https://api.ngc.nvidia.com/v2/models/nvidia/tao/peoplenet/versions/deployable_quantized_v2.6/zip"

        model_file: resnet34_peoplenet_pruned.etlt  # v2.0 Accuracy: 84.3 Size 20.9 MB
        # model_file: resnet34_peoplenet_int8.etlt  # v2.6 Accuracy: 86.0 Size: 85.03 MB

        precision: int8
        int8_calib_file: resnet34_peoplenet_int8.txt
        input:
          layer_name: input_1
          shape: [3, 544, 960]
          scale_factor: 0.0039215697906911373
        output:
          layer_names: [output_bbox/BiasAdd, output_cov/Sigmoid]
          num_detected_classes: 3
          objects:
            - class_id: 0
              label: person
            - class_id: 2
              label: face
              selector:
                kwargs:
                  confidence_threshold: 0.1
