FROM python:3.9.13-slim

ARG PROJECT_PATH=/opt/savant
ENV PYTHONUNBUFFERED=1 \
    PROJECT_PATH=$PROJECT_PATH \
    PYTHONPATH=$PROJECT_PATH \
    RUST_LOG=info
WORKDIR $PROJECT_PATH

COPY adapters/requirements.txt $PROJECT_PATH/adapters/requirements.txt
RUN python -m pip install --no-cache-dir -r $PROJECT_PATH/adapters/requirements.txt
COPY adapters/requirements-py.txt $PROJECT_PATH/adapters/requirements-py.txt
RUN python -m pip install --no-cache-dir -r $PROJECT_PATH/adapters/requirements-py.txt
COPY requirements/savant-rs.txt $PROJECT_PATH/adapters/requirements-savant-rs.txt
RUN pip install --no-cache-dir -r $PROJECT_PATH/adapters/requirements-savant-rs.txt

COPY savant $PROJECT_PATH/savant
COPY adapters/python $PROJECT_PATH/adapters/python
