FROM python:3.9.13-slim

ENV PYTHONUNBUFFERED=1
ARG PROJECT_PATH=/opt/savant
ENV PROJECT_PATH=$PROJECT_PATH
ENV PYTHONPATH=$PROJECT_PATH
WORKDIR $PROJECT_PATH

COPY adapters/requirements.txt $PROJECT_PATH/adapters/requirements.txt
RUN python -m pip install --no-cache-dir -r $PROJECT_PATH/adapters/requirements.txt

COPY savant $PROJECT_PATH/savant
COPY adapters/python $PROJECT_PATH/adapters/python
