ARG DEEPSTREAM_VERSION=6.0.1
FROM nvcr.io/nvidia/deepstream-l4t:$DEEPSTREAM_VERSION-samples AS base_builder

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer1.0-dev \
        python3-dev \
        python3-setuptools \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

# python to python3 by default
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

RUN wget --no-verbose -O /tmp/cmake.sh \
        https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-aarch64.sh  \
    && sh /tmp/cmake.sh --skip-license --prefix=/usr \
    && rm -f /tmp/cmake.sh

ARG soc=t210
ARG l4t_version=32.6

ADD --chown=root:root https://repo.download.nvidia.com/jetson/jetson-ota-public.asc /etc/apt/trusted.gpg.d/jetson-ota-public.asc

RUN chmod 644 /etc/apt/trusted.gpg.d/jetson-ota-public.asc \
    && echo "deb https://repo.download.nvidia.com/jetson/common r$l4t_version main" > /etc/apt/sources.list.d/nvidia-l4t-apt-source.list \
    && echo "deb https://repo.download.nvidia.com/jetson/$soc r$l4t_version main" >> /etc/apt/sources.list.d/nvidia-l4t-apt-source.list \
    && rm /etc/ld.so.conf.d/nvidia-tegra.conf \
    && mkdir -p /opt/nvidia/l4t-packages/ \
    && touch /opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        cuda-toolkit-10-2 \
        nvidia-l4t-multimedia \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp/cub \
    && cd /tmp/cub \
    && wget -c https://github.com/NVIDIA/cub/archive/refs/tags/1.8.0.tar.gz -O - | tar -xz --strip-components 1 \
    && mv /tmp/cub/cub /usr/include/ \
    && ls -al /usr/include/cub


FROM base_builder AS pygstsavantframemeta_build

WORKDIR /libs/gstsavantframemeta
COPY libs/gstsavantframemeta/requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY libs/gstsavantframemeta .
RUN python setup.py bdist_wheel && \
    rm -rf _skbuild


FROM base_builder AS savantboost_build

WORKDIR /libs/savanboost
COPY libs/savantboost/requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

COPY libs/savantboost .
RUN python setup.py bdist_wheel && rm -rf _skbuild


FROM base_builder AS pyds_build

RUN apt-get update \
    && apt-get install -y \
        automake \
        cmake \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer1.0-dev \
        libtool \
        python-dev \
        python-gi-dev \
        python3-dev \
        python3-pip \
        python3-setuptools \
    && rm -rf /var/lib/apt/lists/*

ARG PYDS_TAG=v1.1.1-unmap
RUN git clone https://github.com/tomskikh/deepstream_python_apps.git /deepstream_python_apps \
    && cd /deepstream_python_apps \
    && git checkout $PYDS_TAG \
    && git submodule init \
    && git submodule update \
    && cd 3rdparty/gst-python \
    && git submodule init \
    && git submodule update

WORKDIR /deepstream_python_apps/3rdparty/gst-python
RUN ./autogen.sh \
    && make \
    && make install

WORKDIR /deepstream_python_apps/bindings/build
RUN cmake -DPIP_PLATFORM=linux_aarch64 .. \
    && make \
    && mkdir /dist \
    && mv *.whl /dist/


FROM base_builder AS opencv_build

WORKDIR /opencv
ARG OPENCV_VERSION=4.6.0
RUN git clone --branch "${OPENCV_VERSION}" --depth 1 https://github.com/opencv/opencv
RUN git clone --branch "${OPENCV_VERSION}" --depth 1 https://github.com/opencv/opencv_contrib
WORKDIR /opencv/build

RUN python -m pip install --no-cache-dir --upgrade pip
RUN python -m pip install --no-cache-dir 'numpy==1.19.4'

COPY libs/opencv/savant /opencv/opencv_contrib/modules/savant
RUN --mount=type=cache,target=/tmp/opencv-cache \
    cmake \
        -D CMAKE_BUILD_TYPE=RELEASE \
        -D OPENCV_EXTRA_MODULES_PATH=/opencv/opencv_contrib/modules  \
        -D CMAKE_INSTALL_PREFIX=/opencv/dist  \
        -D OPENCV_DOWNLOAD_PATH=/tmp/opencv-cache \
        -D PYTHON_DEFAULT_EXECUTABLE=$(which python3) \
        -D OPENCV_PYTHON_INSTALL_PATH=lib/python3.8/dist-packages \
        -D OPENCV_FORCE_PYTHON_LIBS=ON \
        -D BUILD_LIST=core,cudaarithm,cudabgsegm,cudacodec,cudafeatures2d,cudafilters,cudaimgproc,cudev,features2d,flann,imgcodecs,savant,python3 \
        -D BUILD_opencv_apps=OFF \
        -D BUILD_DOCS=OFF \
        -D BUILD_EXAMPLES=OFF \
        -D BUILD_JAVA=OFF \
        -D BUILD_PERF_TESTS=OFF \
        -D BUILD_SHARED_LIBS=ON \
        -D WITH_CUDA=ON \
        -D WITH_FFMPEG=OFF \
        -D WITH_GSTREAMER=OFF \
        /opencv/opencv

RUN make -j$(nproc) install


FROM nvcr.io/nvidia/deepstream-l4t:$DEEPSTREAM_VERSION-base AS base

# python2 to python3 by default
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

# apt-get cannot create files in /tmp
RUN chmod 1777 /tmp

# install base packages
RUN rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -y \
        autoconf \
        automake \
        cmake \
        gcc \
        git \
        libcairo2-dev \
        libgirepository1.0-dev \
        libgstreamer1.0-dev \
        gobject-introspection \
        libtool \
        pkg-config \
        python-dev \
        python-gi-dev \
        python-gst-1.0 \
        python3-pip && \
    rm -rf /var/lib/apt/lists/*

# upgrade pip so it can use manylinux2014 to get compiled binaries
RUN python -m pip install --no-cache-dir --upgrade pip
RUN python -m pip install --no-cache-dir numpy==1.19.4
# "Cannot uninstall 'PyGObject'. It is a distutils installed project"
# using already installed version of pygobject and pycairo

# build and install gst-python
RUN apt-get update && \
    apt-get install -y --reinstall ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    cd /tmp && \
    export GST_LIBS="-lgstreamer-1.0 -lgobject-2.0 -lglib-2.0" && \
    export GST_CFLAGS="-pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include" && \
    export PYTHON=/usr/bin/python3 && \
    export LIBPYTHON=$($PYTHON -c 'from distutils import sysconfig; print(sysconfig.get_config_var("LDLIBRARY"))') && \
    export LIBPYTHONPATH=$(dirname $(ldconfig -p | grep -w $LIBPYTHON | head -1 | tr ' ' '\n' | grep /)) && \
    export PYGI_DIRPATH=$($PYTHON -c 'import os;import gi; print(f"{os.path.dirname(gi.__file__)}/overrides")') && \
    git clone https://github.com/GStreamer/gst-python.git && \
    cd gst-python && \
    git checkout 1a8f48a && \
    ./autogen.sh --disable-gtk-doc --noconfigure && \
    ./configure --with-libpython-dir=$LIBPYTHONPATH --libdir=$LIBPYTHONPATH --with-pygi-overrides-dir=$PYGI_DIRPATH && \
    make && \
    make install && \
    make clean && make distclean && \
    cd .. && \
    rm -r gst-python

# Uninstalling apt packages since they have PyGObject==3.26.1 with bugs related
# to translating properties between Python and C. Those bugs cause segfault when
# loading gst-plugins written in python. We needed to install those packages before
# to build gst-python.
RUN apt-get remove -y \
        python-gi \
        python3-gi \
        python-gi-dev
RUN python -m pip install --no-cache-dir pycairo==1.19.0
RUN python -m pip install --no-cache-dir PyGObject==3.40.1

COPY --from=opencv_build /opencv/dist /usr/local

ENV PYTHONUNBUFFERED=1
ARG APP_PATH=/opt/app
ENV APP_PATH=$APP_PATH
ENV PYTHONPATH=$APP_PATH
WORKDIR $APP_PATH

# add deepstream libs to path, so that ctypes can load them
ENV LD_LIBRARY_PATH=/opt/nvidia/deepstream/deepstream/lib/:$LD_LIBRARY_PATH

# install requirements
COPY requirements/base.txt requirements-base.txt
COPY requirements/deepstream-l4t-6.0.1.txt requirements-deepstream-l4t.txt
RUN python -m pip install --no-cache-dir \
    -r requirements-base.txt \
    -r requirements-deepstream-l4t.txt \
    && rm requirements-base.txt \
    && rm requirements-deepstream-l4t.txt

COPY --from=pyds_build /dist /libs/pyds/dist
RUN python -m pip install --no-cache-dir /libs/pyds/dist/*.whl

COPY --from=pygstsavantframemeta_build /libs/gstsavantframemeta/dist /libs/gstsavantframemeta/dist
RUN python -m pip install --no-cache-dir /libs/gstsavantframemeta/dist/*.whl

COPY --from=savantboost_build /libs/savanboost/dist /libs/savanboost/dist
RUN python -m pip install --no-cache-dir /libs/savanboost/dist/*.whl

COPY savant savant
ENV GST_PLUGIN_PATH=$APP_PATH/savant/gst_plugins:$APP_PATH/savant/utils/gst_plugins

COPY LICENSE savant/

ENTRYPOINT ["python", "-m", "savant.entrypoint"]

FROM base as samples
COPY samples samples

FROM base AS adapters

COPY adapters/ds adapters/ds
COPY adapters/gst/gst_plugins/python/adjust_timestamps.py adapters/ds/gst_plugins/python/adjust_timestamps.py
ENV GST_PLUGIN_PATH=$GST_PLUGIN_PATH:$APP_PATH/adapters/ds/gst_plugins

ENTRYPOINT []
