FROM ghcr.io/insight-platform/savant-deepstream:latest

COPY requirements/dev.txt requirements/dev.txt

RUN python -m pip install --no-cache-dir -r requirements/dev.txt
RUN pip3 install torch torchvision torchaudio

#COPY tests /opt/savant/tests

ENTRYPOINT ["pytest", "/opt/savant/tests"]
