name: face_reid_index_builder

parameters:
  frame:
    width: 1280
    height: 720

  face_width: 112
  face_height: 112
  detection_model_name: yolov5nface

  reid_model_name: adaface_ir50_webface4m_90fb74c

pipeline:

  elements:
    # detector
    - element: nvinfer@complex_model
      name: ${parameters.detection_model_name}
      model:
        remote:
          url: s3://savant-data/models/yolov5face/${parameters.detection_model_name}.zip
          checksum_url: s3://savant-data/models/yolov5face/${parameters.detection_model_name}.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        config_file: yolov5n-face.txt
        input:
          shape: [3, 640, 640]
        output:
          layer_names: [ 'output' ]
          converter:
            module: savant.converter.yolo_v5face
            class_name: YoloV5faceConverter
            kwargs:
              confidence_threshold: 0.6
              nms_iou_threshold: 0.5
          objects:
            - class_id: 0
              label: face
              selector:
                module: savant.selector.detector
                class_name: MinMaxSizeBBoxSelector
                kwargs:
                  min_width: 40
                  min_height: 40
          attributes:
            - name: landmarks

    - element: nvinfer@attribute_model
      name: ${parameters.reid_model_name}
      model:
        remote:
          url: s3://savant-data/models/${parameters.reid_model_name}/${parameters.reid_model_name}.zip
          checksum_url: s3://savant-data/models/${parameters.reid_model_name}/${parameters.reid_model_name}.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        model_file: adaface_ir50_webface4m.onnx
        input:
          object: ${parameters.detection_model_name}.face
          shape: [3, 112, 112]
          offsets: [127.5, 127.5, 127.5]
          scale_factor: 0.007843137254902
          color_format: bgr
          preprocess_object_image:
            module: samples.face_reid.face_preproc
            class_name: FacePreprocessingObjectImageGPU
        output:
          layer_names: [ 'feature', 'norm' ]
          converter:
            module: savant.converter
            class_name: TensorToVectorConverter
          attributes:
            - name: feature

    - element: pyfunc
      module: samples.face_reid.index_builder
      class_name: IndexBuilder
      kwargs:
        index_dir: /opt/savant/samples/face_reid/index_files/
        index_space: cosine
        # index_dim is set according to the reid model output dimensions
        index_dim: 512
        # hnswlib index parameters
        # for details refer to hnswlib doc
        # https://github.com/nmslib/hnswlib#api-description
        index_max_elements: 100
        index_ef_construction: 200
        index_m: 16

  # output sink adapter is not used
  sink:
    - element: devnull_sink
