name: ${oc.env:MODULE_NAME, 'nvidia_car_classification'}

parameters:
  output_frame: ${json:${oc.env:OUTPUT_FRAME, '{"codec":"raw-rgba"}'}}
  draw_func:
    module: samples.nvidia_car_classification.overlay
    # specify the drawfunc's python class from the module
    class_name: Overlay

pipeline:

  elements:

    # detector
    - element: nvinfer@detector
      name: Primary_Detector
      model:
        format: caffe
        remote:
          url: s3://savant-data/models/Primary_Detector/Primary_Detector.zip
          checksum_url: s3://savant-data/models/Primary_Detector/Primary_Detector.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        config_file: ${oc.env:APP_PATH}/samples/nvidia_car_classification/dstest2_pgie_config.txt

    # tracker
    - element: nvtracker
      properties:
        tracker-width: 640
        tracker-height: 384
        ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
        ll-config-file: ${oc.env:APP_PATH}/samples/nvidia_car_classification/config_tracker_NvDCF_perf.yml
        #enable_past_frame: 1
        enable_batch_process: 1
        #display-tracking-id: 0

    # Car Color classifier
    - element: nvinfer@classifier
      name: Secondary_CarColor
      model:
        format: caffe
        remote:
          url: s3://savant-data/models/Secondary_CarColor/Secondary_CarColor.zip
          checksum_url: s3://savant-data/models/Secondary_CarColor/Secondary_CarColor.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        config_file: ${oc.env:APP_PATH}/samples/nvidia_car_classification/dstest2_sgie1_config.txt
        input:
          object: Primary_Detector.Car
        output:
          attributes:
            - name: car_color

    # Car Make classifier
    - element: nvinfer@classifier
      name: Secondary_CarMake
      model:
        format: caffe
        remote:
          url: s3://savant-data/models/Secondary_CarMake/Secondary_CarMake.zip
          checksum_url: s3://savant-data/models/Secondary_CarMake/Secondary_CarMake.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        config_file: ${oc.env:APP_PATH}/samples/nvidia_car_classification/dstest2_sgie2_config.txt
        input:
          object: Primary_Detector.Car
        output:
          attributes:
            - name: car_make

    # Car Type classifier
    - element: nvinfer@classifier
      name: Secondary_VehicleTypes
      model:
        format: caffe
        remote:
          url: s3://savant-data/models/Secondary_VehicleTypes/Secondary_VehicleTypes.zip
          checksum_url: s3://savant-data/models/Secondary_VehicleTypes/Secondary_VehicleTypes.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        config_file: ${oc.env:APP_PATH}/samples/nvidia_car_classification/dstest2_sgie3_config.txt
        input:
          object: Primary_Detector.Car
        output:
          attributes:
            - name: car_type
