FROM ghcr.io/insight-platform/savant-deepstream:0.2.2-6.2

COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

COPY module module
WORKDIR /opt/savant/module

ENTRYPOINT ["./run.py"]
