FROM ghcr.io/insight-platform/savant-deepstream:latest

RUN pip3 install torch torchvision torchaudio

ENV TORCH_HOME=/models/torch
RUN export PYTHONPATH=/models/yolov7:$PYTHONPATH

RUN pip3 install prefetch_generator matplotlib yacs

