services:

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.15
    extends:
      file: docker-compose.l4t.yml
      service: video-loop-source

  module-detector:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream:0.5.15-7.0
    extends:
      file: docker-compose.l4t.yml
      service: module-detector
    runtime: runc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  module-tracker:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream:0.5.15-7.0
    extends:
      file: docker-compose.l4t.yml
      service: module-tracker
    runtime: runc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  module-draw-func:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream:0.5.15-7.0
    extends:
      file: docker-compose.l4t.yml
      service: module-draw-func
    runtime: runc
    environment:
      - CODEC=h264
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  always-on-sink:
    privileged: true
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.5.15-7.0
    extends:
      file: docker-compose.l4t.yml
      service: always-on-sink
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  prometheus:
    extends:
      file: docker-compose.l4t.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.l4t.yml
      service: grafana

volumes:
  zmq_sockets:
