name: yolov11_seg

parameters:
  sampling_fps: ${oc.decode:${oc.env:SAMPLING_FPS, 10}}
  roi:
    left: ${oc.decode:${oc.env:ROI_LEFT, 100}}
    top: ${oc.decode:${oc.env:ROI_TOP, 100}}
    width: ${oc.decode:${oc.env:ROI_WIDTH, 1080}}
    height: ${oc.decode:${oc.env:ROI_HEIGHT, 520}}
  frame:
    width: 1280
    height: 720
  output_frame: ${py:samples.yolov11_seg.module.converter_opt, output_frame_selector}
  draw_func:
    module: samples.yolov11_seg.module.overlay
    class_name: Overlay
    condition:
      tag: visualize
    kwargs:
      roi_left: ${parameters.roi.left}
      roi_top: ${parameters.roi.top}
      roi_width: ${parameters.roi.width}
      roi_height: ${parameters.roi.height}
      mask_color: [0, 255, 0, 64]
      bg_color: [0, 0, 0, 0] # transparent
    rendered_objects:
      segmenter:
        person:
          bbox:
            border_color: '00FF00FF'  # Green
            background_color: '000000AA'  # semi-transparent black
            thickness: 2
          label:
            format: [ '{label}' ]
            font_color: 'FFFFFFFF' # White
            background_color: '000000AA' # semi-transparent black
            border_width: 2
            border_color: 'FFFFFFFF' # white
            position:
              position: TopLeftOutside
              margin_x: 0
              margin_y: -10
      rate_limiter:
        roi:
          bbox:
            border_color: 'FF0000FF'  # Red
            background_color: '00000000' # transparent
            thickness: 2
          label:
            font_color: 'FFFFFFFF' # White
            background_color: '000000AA' # semi-transparent black
            format: [ '{label}' ]
            border_width: 2
            border_color: 'FFFFFFFF' # white
            padding: [15, 15, 15, 15]
            position:
              position: TopLeftOutside
              margin_x: -40
              margin_y: 30
  buffer_queues:
    length: 10
  batch_size: 1
  model_output_converter: ${py:samples.yolov11_seg.module.converter_opt, converter_selector}

pipeline:
  elements:
    - element: pyfunc
      module: samples.yolov11_seg.module.sampler
      class_name: Downsampler
      kwargs:
        sampling_fps: ${parameters.sampling_fps}
        roi_left: ${parameters.roi.left}
        roi_top: ${parameters.roi.top}
        roi_width: ${parameters.roi.width}
        roi_height: ${parameters.roi.height}
    - element: nvinfer@instance_segmentation
      name: segmenter
      model:
        remote:
          url: s3://savant-data/models/yolov11-seg/yolo11m-seg.zip
          checksum_url: s3://savant-data/models/yolov11-seg/yolo11m-seg.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        model_file: yolo11m-seg.onnx
        batch_size: ${parameters.batch_size}
        input:
          object: rate_limiter.roi
          shape: [3, 640, 640]
          maintain_aspect_ratio: true
          scale_factor: 0.0039215697906911373
          offsets: [0.0, 0.0, 0.0]
        output:
          layer_names: [output0, output1]
          converter:
            module: samples.yolov11_seg.module.${parameters.model_output_converter}
            class_name: TensorToBBoxSegConverter
            kwargs:
              confidence_threshold: 0.7
              nms_iou_threshold: 0.45
          num_detected_classes: 80  # COCO classes
          objects:
            - class_id: 0
              label: person
              selector:
                module: savant.selector.detector
                class_name: MinMaxSizeBBoxSelector
                kwargs:
                  min_height: 64
          attributes:
            - name: mask
              # must be internal, output schema doesn't currently support numpy arrays
              internal: true
