services:
  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer-l4t:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - /tmp/video-loop-source-downloads:/tmp/video-loop-source-downloads
    environment:
      - LOCATION=${VIDEO_LOCATION:-https://eu-central-1.linodeobjects.com/savant-data/demo/shuffle_dance_dup.mp4}
      - DOWNLOAD_PATH=/tmp/video-loop-source-downloads
      - ZMQ_ENDPOINT=dealer+connect:ipc:///tmp/zmq-sockets/input-video.ipc
      - SOURCE_ID=video
      - SYNC_OUTPUT=True
    entrypoint: /opt/savant/adapters/gst/sources/video_loop.sh
    depends_on:
      always-on-sink:
        condition: service_started

  router:
    image: ghcr.io/insight-platform/savant-router-arm64:savant-latest
    restart: unless-stopped
    volumes:
      - ./src/router/config.json:/opt/etc/configuration.json:ro
      - ./src:/opt/python:ro
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - PYTHON_MODULE_ROOT=/opt/python
      - ZMQ_INGRESS=router+bind:ipc:///tmp/zmq-sockets/input-video.ipc
      - ZMQ_EGRESS_LEFT=dealer+bind:ipc:///tmp/zmq-sockets/left.ipc
      - ZMQ_EGRESS_RIGHT=dealer+bind:ipc:///tmp/zmq-sockets/right.ipc
    depends_on:
      module-left:
        condition: service_healthy
      module-right:
        condition: service_healthy

  module-left:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream-l4t:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../cache:/cache
      - ..:/opt/savant/samples
    command: samples/meta_merge/src/detector/module.yml
    environment:
      - LOGLEVEL=info
      - MODEL_PATH=/cache/models/meta_merge
      - DOWNLOAD_PATH=/cache/downloads/meta_merge
      - ZMQ_SRC_ENDPOINT=router+connect:ipc:///tmp/zmq-sockets/left.ipc
      - ZMQ_SINK_ENDPOINT=dealer+connect:ipc:///tmp/zmq-sockets/meta_merge_left.ipc
      - MODULE_ROI=left
      - CODEC=copy
      - METRICS_FRAME_PERIOD=1000
    runtime: nvidia

  module-right:
    privileged: true
    image: ghcr.io/insight-platform/savant-deepstream-l4t:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../../cache:/cache
      - ..:/opt/savant/samples
    command: samples/meta_merge/src/detector/module.yml
    environment:
      - LOGLEVEL=info
      - MODEL_PATH=/cache/models/meta_merge
      - DOWNLOAD_PATH=/cache/downloads/meta_merge
      - ZMQ_SRC_ENDPOINT=router+connect:ipc:///tmp/zmq-sockets/right.ipc
      - ZMQ_SINK_ENDPOINT=dealer+connect:ipc:///tmp/zmq-sockets/meta_merge_right.ipc
      - MODULE_ROI=right
      - CODEC=copy
      - METRICS_FRAME_PERIOD=1000
    runtime: nvidia
    depends_on:
      module-left:
        condition: service_healthy

  meta-merge:
    image: ghcr.io/insight-platform/savant-meta-merge-arm64:savant-latest
    restart: unless-stopped
    volumes:
      - ./src/meta_merge/config.json:/opt/etc/configuration.json:ro
      - ./src/meta_merge:/opt/python:ro
      - zmq_sockets:/tmp/zmq-sockets
    environment:
      - PYTHON_MODULE_ROOT=/opt/python
      - ZMQ_INGRESS_LEFT=router+bind:ipc:///tmp/zmq-sockets/meta_merge_left.ipc
      - ZMQ_INGRESS_RIGHT=router+bind:ipc:///tmp/zmq-sockets/meta_merge_right.ipc
      - ZMQ_EGRESS=dealer+bind:ipc:///tmp/zmq-sockets/meta_merge_output.ipc
    depends_on:
      module-left:
        condition: service_healthy
      module-right:
        condition: service_healthy

  visualization:
    privileged: true
    runtime: nvidia
    image: ghcr.io/insight-platform/savant-deepstream-l4t:latest
    restart: unless-stopped
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ..:/opt/savant/samples
    command: samples/meta_merge/src/visualization/module.yml
    environment:
      - LOGLEVEL=info
      - ZMQ_SRC_ENDPOINT=router+connect:ipc:///tmp/zmq-sockets/meta_merge_output.ipc
      - ZMQ_SINK_ENDPOINT=dealer+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - CODEC=jpeg
      - METRICS_FRAME_PERIOD=1000
    depends_on:
      meta-merge:
        condition: service_started

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream-l4t:latest
    restart: unless-stopped
    ports:
      - "554:554"
      - "1935:1935"
      - "888:888"
      - "8889:8889"
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=router+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=video
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_2560x720.jpeg
      - DEV_MODE=True
      - FRAMERATE=30/1
      - ENCODER_BITRATE=8000000
      - LATENCY_MS=5000
      - ENCODER_PROFILE=High
    command: python -m adapters.ds.sinks.always_on_rtsp
    runtime: nvidia
    depends_on:
      visualization:
        condition: service_healthy

volumes:
  zmq_sockets:
