services:

  module:
    image: ghcr.io/insight-platform/savant-deepstream:0.6.0-7.1
    restart: unless-stopped
    privileged: true
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ..:/opt/savant/samples
      - ../../data:/data
    environment:
      - URI
      - ZMQ_SINK_ENDPOINT=dealer+connect:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=video-source-1
      - METRICS_FRAME_PERIOD=100000
    command: samples/uridecodebin/src/module.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.6.0-7.1
    restart: unless-stopped
    ports:
      - "554:554"    # RTSP
      - "1935:1935"  # RTMP
      - "888:888"    # HLS
      - "8889:8889"  # WebRTC
    volumes:
      - zmq_sockets:/tmp/zmq-sockets
      - ../assets/stub_imgs:/stub_imgs
    environment:
      - ZMQ_ENDPOINT=router+bind:ipc:///tmp/zmq-sockets/output-video.ipc
      - SOURCE_ID=video-source-1
      - FRAMERATE=30/1
      - STUB_FILE_LOCATION=/stub_imgs/smpte100_1280x720.jpeg
      - DEV_MODE=True
    command: python -m adapters.ds.sinks.always_on_rtsp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]


volumes:
  zmq_sockets:
