# module name, required
name: ${oc.env:MODULE_NAME, 'demo'}

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
    # Add paddings to the frame before processing
    padding:
      # Paddings are kept on the output frame
      keep: true
      left: 0
      right: 1280
      # Padding size is 180px on the top of the frame
      top: 0
      bottom: 0
  output_frame:
    # Frame is output without any encoding
    # this is to circumvent 3 hardware decoding processes limit on NVIDIA consumer hardware
    codec: raw-rgba
  # PyFunc for drawing on frames
  batch_size: 1
  draw_func: {}


# pipeline definition
pipeline:
  # local video file source, not using source adapter
  source:
    element: uridecodebin
    properties:
      uri: file:///data/road_traffic.mp4

  # define pipeline's main elements
  elements:
    - element: pyfunc
      # specify the pyfunc's python module
      module: samples.background_remover.bgremover
      # specify the pyfunc's python class from the module
      class_name: BgRemover

  # noop pipeline sink, not using sink adapter
  sink:
    - element: devnull_sink
