services:
  kafka:
    extends:
      file: docker-compose-no-keydb.l4t.yml
      service: kafka

  video-loop-source:
    image: ghcr.io/insight-platform/savant-adapters-gstreamer:0.5.10
    extends:
      file: docker-compose-no-keydb.l4t.yml
      service: video-loop-source

  kafka-sink:
    image: ghcr.io/insight-platform/savant-adapters-py:0.5.10
    extends:
      file: docker-compose-no-keydb.l4t.yml
      service: kafka-sink

  kafka-source:
    image: ghcr.io/insight-platform/savant-adapters-py:0.5.10
    extends:
      file: docker-compose-no-keydb.l4t.yml
      service: kafka-source

  module:
    image: ghcr.io/insight-platform/savant-deepstream:0.5.10-7.0
    extends:
      file: docker-compose-no-keydb.l4t.yml
      service: module
    runtime: runc
    environment:
      - CODEC=h264
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  always-on-sink:
    image: ghcr.io/insight-platform/savant-adapters-deepstream:0.5.10-7.0
    extends:
      file: docker-compose-no-keydb.l4t.yml
      service: always-on-sink
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  kafka_data:
  zmq_sockets:
