# module name, required
name: source_shaper_sample

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    shaper:
      module: samples.source_shaper_sample.custom_source_shaper
      class_name: CustomSourceShaper
      kwargs:
        sources:
          city-traffic:
            width: 1440
            height: 800
            padding:
              right: 80
              top: 160
          town-centre:
            width: 960
            height: 544
            padding:
              left: 64
  output_frame:
    # Frame is output without any encoding
    # this is to circumvent 3 hardware decoding processes limit on NVIDIA consumer hardware
    codec: ${oc.env:CODEC, 'h264'}
  batch_size: 1
