# module name, required
name: kvs-sample

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
  output_frame:
    codec: ${oc.env:CODEC, 'h264'}
  batch_size: 1

# pipeline definition
pipeline:
  # source definition is skipped, zeromq source is used by default to connect with source adapters

  # define pipeline's main elements
  elements:
    - element: nvinfer@detector
      name: peoplenet
      model:
        format: etlt
        remote:
          url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.zip
          checksum_url: s3://savant-data/models/peoplenet/peoplenet_pruned_v2.0.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        model_file: resnet34_peoplenet_pruned.etlt
        input:
          layer_name: input_1
          shape: [ 3, 544, 960 ]
          scale_factor: 0.0039215697906911373
        output:
          layer_names: [ output_bbox/BiasAdd, output_cov/Sigmoid ]
          num_detected_classes: 3
          objects:
            - class_id: 0
              label: person

    - element: pyfunc
      module: samples.kvs.mongo_meta_exporter
      class_name: MongoMetaExporter
      kwargs:
        uri: ${oc.decode:${oc.env:MONGO_URI}}
        collection: ${oc.decode:${oc.env:MONGO_COLLECTION}}
        db: ${oc.decode:${oc.env:MONGO_DB}}

  # sink definition is skipped, zeromq sink is used by default to connect with sink adapters
