# build nvinfer custom library for yolo models (create engine and parse bbox functions)
# https://github.com/marcoslucianops/DeepStream-Yolo
# build custom parser for licence plate recognition model
ARG DS_YOLO_PATH=/opt/yolo
ARG DS_LPR_APP_PATH=/opt/lpr
ARG NVDSINFER_PATH=/opt/nvidia/deepstream/deepstream/sources/libs/nvdsinfer

FROM nvcr.io/nvidia/deepstream:6.3-triton-multiarch as builder

ENV CUDA_VER=11.4
ARG DS_YOLO_VER=000bcd676d48eb236076aed111ab23ff0105de3d
ARG DS_LPR_APP_VER=9c761e5ec9fea5ac4c6e3f4357326693d2d3cf48
ARG DS_YOLO_PATH
ARG DS_LPR_APP_PATH
ARG NVDSINFER_PATH

RUN git clone https://github.com/NVIDIA-AI-IOT/deepstream_lpr_app.git $DS_LPR_APP_PATH \
    && cd $DS_LPR_APP_PATH \
    && git checkout $DS_LPR_APP_VER \
    && cd $DS_LPR_APP_PATH/nvinfer_custom_lpr_parser \
    && make

RUN git clone https://github.com/marcoslucianops/DeepStream-Yolo.git $DS_YOLO_PATH \
    && cd $DS_YOLO_PATH \
    && git checkout $DS_YOLO_VER \
    && make -C nvdsinfer_custom_impl_Yolo

# patch nvdsinfer_model_builder.cpp: use engine path to place created engine
COPY nvdsinfer_model_builder.patch $NVDSINFER_PATH/
RUN cd $NVDSINFER_PATH && \
    patch nvdsinfer_model_builder.cpp < nvdsinfer_model_builder.patch && \
    make

FROM ghcr.io/insight-platform/savant-deepstream-l4t:0.2.8-6.3

ARG DS_YOLO_PATH
ARG DS_LPR_APP_PATH
ARG NVDSINFER_PATH

COPY --from=builder $DS_YOLO_PATH/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so /opt/savant/lib/
COPY --from=builder $DS_LPR_APP_PATH/nvinfer_custom_lpr_parser/libnvdsinfer_custom_impl_lpr.so /opt/savant/lib/
COPY --from=builder $NVDSINFER_PATH/libnvds_infer.so /opt/nvidia/deepstream/deepstream/lib/
COPY --from=builder $DS_LPR_APP_PATH/deepstream-lpr-app/dict_us.txt /opt/savant/dict.txt
