name: ${oc.env:MODULE_NAME, 'yolov8_seg'}

parameters:
  frame:
    width: 1280
    height: 720
  draw_func:
    module: samples.yolov8_seg.module.overlay
    class_name: Overlay
  buffer_queues:
    length: 10
  batch_size: 1

pipeline:
  source:
    element: uridecodebin
    properties:
      uri: file:///data/shuffle_dance.mp4

  elements:
    - element: nvinfer@instance_segmentation
      name: yolov8_seg
      model:
        remote:
          url: s3://savant-data/models/yolov8m_seg/yolov8m_seg.zip
          checksum_url: s3://savant-data/models/yolov8m_seg/yolov8m_seg.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        model_file: yolov8m-seg.onnx
        batch_size: ${parameters.batch_size}
        input:
          shape: [3, 640, 640]
          maintain_aspect_ratio: true
          scale_factor: 0.0039215697906911373
          offsets: [0.0, 0.0, 0.0]
        output:
          layer_names: [output0, output1]
          converter:
            module: samples.yolov8_seg.module.converter
            class_name: TensorToBBoxSegConverter
            kwargs:
              confidence_threshold: 0.7
              nms_iou_threshold: 0.45
          num_detected_classes: 80
          objects:
            - class_id: 0
              label: person
              selector:
                module: savant.selector.detector
                class_name: MinMaxSizeBBoxSelector
                kwargs:
                  min_height: 64
          attributes:
            - name: mask
              # must be internal, output schema doesn't currently support numpy arrays
              internal: true

  sink:
    - element: devnull_sink
