name: yolov8_seg

parameters:
  sampling_fps: ${oc.decode:${oc.env:SAMPLING_FPS, 10}}
  roi:
    left: ${oc.decode:${oc.env:ROI_LEFT, 100}}
    top: ${oc.decode:${oc.env:ROI_TOP, 100}}
    width: ${oc.decode:${oc.env:ROI_WIDTH, 1080}}
    height: ${oc.decode:${oc.env:ROI_HEIGHT, 520}}
  frame:
    width: 1280
    height: 720
  output_frame:
    codec: ${oc.env:CODEC, 'hevc'}
    condition:
      tag: visualize
  draw_func:
    module: samples.yolov8_seg.module.overlay
    class_name: Overlay
    condition:
      tag: visualize
    kwargs:
      roi_left: ${parameters.roi.left}
      roi_top: ${parameters.roi.top}
      roi_width: ${parameters.roi.width}
      roi_height: ${parameters.roi.height}
  buffer_queues:
    length: 10
  batch_size: 1
  model_output_converter: ${oc.env:MODEL_OUTPUT_CONVERTER, converter}

pipeline:
  elements:
    - element: pyfunc
      module: samples.yolov8_seg.module.sampler
      class_name: Downsampler
      kwargs:
        sampling_fps: ${parameters.sampling_fps}
        roi_left: ${parameters.roi.left}
        roi_top: ${parameters.roi.top}
        roi_width: ${parameters.roi.width}
        roi_height: ${parameters.roi.height}
    - element: nvinfer@instance_segmentation
      name: yolov8_seg
      model:
        remote:
          url: s3://savant-data/models/yolov8m_seg/yolov8m_seg.zip
          checksum_url: s3://savant-data/models/yolov8m_seg/yolov8m_seg.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        model_file: yolov8m-seg.onnx
        batch_size: ${parameters.batch_size}
        input:
          object: rate_limiter.roi
          shape: [3, 640, 640]
          maintain_aspect_ratio: true
          scale_factor: 0.0039215697906911373
          offsets: [0.0, 0.0, 0.0]
        output:
          layer_names: [output0, output1]
          converter:
            module: samples.yolov8_seg.module.${parameters.model_output_converter}
            class_name: TensorToBBoxSegConverter
            kwargs:
              confidence_threshold: 0.7
              nms_iou_threshold: 0.45
          num_detected_classes: 80  # COCO classes
          objects:
            - class_id: 0
              label: person
              selector:
                module: savant.selector.detector
                class_name: MinMaxSizeBBoxSelector
                kwargs:
                  min_height: 64
          attributes:
            - name: mask
              # must be internal, output schema doesn't currently support numpy arrays
              internal: true
