name: ${oc.env:MODULE_NAME, 'yolov8_seg'}

parameters:
  frame:
    width: 1280
    height: 720
  output_frame:
    codec: hevc
  draw_func:
    module: samples.yolov8_seg.module.overlay
    class_name: Overlay

pipeline:
  source:
    element: uridecodebin
    properties:
#      uri: file:///data/images/zidane.png
      uri: file:///data/shuffle_dance.mp4

  elements:
    - element: nvinfer@instance_segmentation
      name: yolov8_seg
      model:
        format: onnx
        model_file: yolov8m-seg.onnx
        input:
          shape: [3, 640, 640]
          # symmetric-padding: true == letterbox
          maintain_aspect_ratio: true
          scale_factor: 0.0039215697906911373
          offsets: [0.0, 0.0, 0.0]

        output:
          layer_names: [output0, output1]
          converter:
            module: samples.yolov8_seg.module.converter
            class_name: TensorToBBoxSegConverter
            kwargs:
              confidence_threshold: 0.7
              nms_iou_threshold: 0.45

          num_detected_classes: 80
          # COCO {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
          objects:
            - class_id: 0
              label: person
              selector:
                module: savant.selector.detector
                class_name: MinMaxSizeBBoxSelector
                kwargs:
                  min_height: 64

          attributes:
            - name: mask
              # must be internal, output schema doesn't currently support numpy arrays
              internal: true

#    - element: queue

#  sink:
#    - element: devnull_sink
#    - element: console_sink
#      properties:
#        json_mode: true
