name: ${oc.env:MODULE_NAME, 'keypoint_detection'}

parameters:
  output_frame:
    codec: h264
  frame:
    width: ${oc.decode:${oc.env:FRAME_WIDTH, 1280}}
    height: ${oc.decode:${oc.env:FRAME_HEIGHT, 720}}
  draw_func:
    module: samples.keypoint_detection.overlay
    class_name: Overlay
    rendered_objects:
      yolov8npose:
        person:
          bbox:
            border_color: '00FF00FF'  # Green
            background_color: '00000000'  # transparent
            thickness: 4
  detected_object:
    id: 0
    label: person

pipeline:
  elements:
    - element: nvinfer@complex_model
      name: yolov8npose
      model:
        remote:
          url: s3://savant-data/models/yolov8npose/yolov8npose.zip
          checksum_url: s3://savant-data/models/yolov8npose/yolov8npose.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: onnx
        model_file: yolov8n-pose.onnx
        config_file: config_infer_primary_yoloV8_pose.txt
        input:
          shape: [ 3, 640, 640 ]
        # max GPU RAM used to build the engine, 6GB by default
        # set lower than total GPU RAM available on your hardware
        workspace_size: 6144
        output:
          layer_names: [ 'boxes', 'scores', 'kpts' ]
          converter:
            module: samples.keypoint_detection.yolo_v8pose
            class_name: YoloV8faceConverter
            kwargs:
              confidence_threshold: 0.6
              nms_iou_threshold: 0.45
          objects:
            - class_id: ${parameters.detected_object.id}
              label: ${parameters.detected_object.label}
              selector:
                module: savant.selector.detector
                class_name: MinMaxSizeBBoxSelector
                kwargs:
                  min_width: 40
                  min_height: 40
          attributes:
            - name: keypoint
