# module name, required
name: ${oc.env:MODULE_NAME, 'demo'}

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
    # Add paddings to the frame before processing
    padding:
      # Paddings are kept on the output frame
      keep: true
      left: 0
      right: 1280
      # Padding size is 180px on the top of the frame
      top: 0
      bottom: 0
  output_frame:
    codec: hevc
  batch_size: 4

  buffer_queues: ${json:${oc.env:BUFFER_QUEUES, null}}
  fps_period: 100000
  # Shutdown the module by receiving a specific message from source adapter
  shutdown_auth: opencv_cuda_bg_remover_mog2


# pipeline definition
pipeline:
  # define pipeline's main elements
  elements:
    - element: pyfunc
      # specify the pyfunc's python module
      module: samples.opencv_cuda_bg_remover_mog2.bgremover
      # specify the pyfunc's python class from the module
      class_name: BgRemover

  # noop pipeline sink, not using sink adapter
  sink:
    - element: devnull_sink
