{
 "title": "Module performance metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "record_type", "query": { "query": "label_values(record_type)" } },
   { "name": "extra_labels" }
  ]
 },
 "panels": [
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(frame_counter_total{instance=~\"$instance\", record_type=~\"$record_type\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(object_counter_total{instance=~\"$instance\", record_type=~\"$record_type\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "stage_queue_length{instance=~\"$instance\", record_type=~\"$record_type\"}",
     "legendFormat": "{{instance}}/{{stage_name}}"
    }
   ]
  },
  {
   "title": "Total objects processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "object_counter_total{instance=~\"$instance\", record_type=~\"$record_type\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total frames processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frame_counter_total{instance=~\"$instance\", record_type=~\"$record_type\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}