# module name, required
name: ${oc.env:MODULE_NAME, 'demo'}

# base module parameters
parameters:
  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
  output_frame:
    codec: jpeg
  # PyFunc for drawing on frames (default implementation)
  draw_func:
    rendered_objects:
      yolov8m:
        person:
          bbox:
            border_color: 'FF0000FF'  # Red
            background_color: '00000000'  # transparent
            thickness: 5
          label:
            # RGBA color values for person label's font and background
            font_color: '000000ff'
            background_color: 'FF0000FF'
            position:
              position: 'TopLeftInside'
      coco:
        person:
          bbox:
            border_color: '00FF00FF'  # Green
            background_color: '00000000'  # transparent
            thickness: 5
            padding:
              top: 10
              left: 10
              bottom: 10
              right: 10



  detected_object:
    id: 0
    label: person
    # id: 2
    # label: car

  batch_size: 1

# pipeline definition
pipeline:
  # source definition is skipped, zeromq source is used by default to connect with source adapters

  # define pipeline's main elements
  elements:
    # primary detector element, inference is provided by the nvinfer Deepstream element
    # model type is detector (other available types are: classifier, custom)
#    - element: pyfunc
#      module: samples.json_input.check
#      class_name: Check
#      kwargs:
#        name_output: test
    # detector
    - element: nvinfer@detector
      name: yolov8m
      model:
        remote:
          url: s3://savant-data/models/yolov8m/yolov8m.zip
          checksum_url: s3://savant-data/models/yolov8m/yolov8m.md5
          parameters:
            endpoint: https://eu-central-1.linodeobjects.com
        format: custom
        config_file: config_infer_primary_yoloV8.txt
        custom_lib_path: /opt/savant/lib/libnvdsinfer_custom_impl_Yolo.so
        output:
          objects:
            - class_id: ${parameters.detected_object.id}
              label: ${parameters.detected_object.label}