# module name, required
name: nvarguscamerasrc
# base module parameters
parameters:
  batch_size: 2
  output_frame:
    codec: jpeg
    #codec: hevc # if you are on NX/AGX
    hevc_encoder_params:
      profile: Main
      bitrate: 8000000
    jpeg_encoder_params:
      quality: 95
  draw_func: null
pipeline:
  source:
    # use
    # v4l2-ctl -d /dev/video0 --list-formats-ext
    # to determine camera formats and max fps
    element: nvarguscamerasrc_bin
    properties:
      sources:
        - source-id: argus-0
          framerate: 5/1
          properties:
            sensor-id: 0
            sensor-mode: 1
        - source-id: argus-1
          framerate: 5/1
          properties:
            sensor-id: 1
            sensor-mode: 1
  sink:
    - element: zeromq_sink
      properties:
        socket: ${oc.env:ZMQ_SINK_ENDPOINT}
