name: Build and publish docker images

on:
  push:
    tags:
      - 'v*'

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-matrix:
#    strategy:
#      fail-fast: false
#      matrix:
#        version: [0.1.0-6.1-base, 0.1.0-6.1-samples]
#        arch: [linux/amd64, linux/arm64]
#        include:
#          - name: savant-deepstream
#            tag: 0.1.0-6.1-base
#            arch: linux/amd64
#          - name: savant-deepstream
#            tag: 0.1.0-6.1-samples
#            arch: linux/amd64
#          - name: savant-deepstream-l4t
#            tag: 0.1.0-6.1-base
#            arch: linux/arm64
#          - name: savant-deepstream-l4t
#            tag: 0.1.0-6.1-samples
#            arch: linux/arm64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup matrix
      id: set-matrix
      run: |
        echo "::set-output name=matrix::$(python3 ./scripts/build_docker_matrix.py)"

  build-docker:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
    - run: |
        echo ${{ matrix.version }}
        echo ${{ matrix.arch }}

